### ISSUE TITLE
Something went wrong

### ISSUE THREAD

**Issue by basim1971** [codefori/vscode-db2i#100]
Dear all,

After connect to Ibm I system  i got this error. 
It' s seem that i m not able to retrieve this json document.
Pc access to internet using a proxy, so i don't know if this could be the problem... Anyway i  can update all the addins so it's seem that if i have a problem linked to proxy it's related only to this 
Any idea to solve it ?

Thanks 

{"name":"HttpError","status":500,"request":{"method":"GET","url":"https://api.github.com/repos/ThePrez/CodeForIBMiServer/releases/tags/v1.0.0-alpha-33","headers":{"accept":"application/vnd.github.v3+json","user-agent":"octokit.js/2.0.14 octokit-core.js/4.2.0 Node.js/16.14.2 (win32; x64)","x-github-api-version":"2022-11-28"},"request":{"retryCount":3,"retries":3,"retryAfter":16}}}

**Comment by ThePrez** [comment]
As you probably already know, HTTP error 500 is an internal server from GitHub. 
First thing I'd go for is simply trying again. Hopefully it was just GitHub being flaky and it resolved itself. 

Otherwise, maybe it is something going on with an HTTP proxy or something else in your infrastructure. 
You could try downloading the file outside of VSCode to see if you get a similar error, for instance running the following from a command line:
```
curl https://api.github.com/repos/ThePrez/CodeForIBMiServer/releases/tags/v1.0.0-alpha-33
```
or opening https://api.github.com/repos/ThePrez/CodeForIBMiServer/releases/tags/v1.0.0-alpha-33 in a browser

**Comment by basim1971** [comment]
Thanks for your reply.  I can reach the file so i exclude is something related my infrastructure. In any case do you know where i need to place this file .. Probably i can do it manualy 

Thanks

**Comment by ThePrez** [comment]
You can manually install the file by downloading from the [GitHub releases page](https://github.com/ThePrez/CodeForIBMiServer/releases) and creating a `$HOME/.vscode` directory and storing the file there. For instance, `$HOME/.vscode/codeforiserver-1.0.0-alpha-33.jar`)

Please note, however, that new releases of the `vscode-db2i` extension often require new versions of this server component, so you will need to redo this operation with every release

**Comment by lostromich** [comment]
Hello
          it seem i have similar issue and getting error:
{"name":"HttpError","status":500,"request":{"method":"GET","url":"https://api.github.com/repos/ThePrez/CodeForIBMiServer/releases/tags/v1.2.0","headers":{"accept":"application/vnd.github.v3+json","user-agent":"octokit.js/2.0.14 octokit-core.js/4.2.0 Node.js/16.14.2 (win32; x64)","x-github-api-version":"2022-11-28"},"request":{"retryCount":3,"retries":3,"retryAfter":16}}}
  I  downloaded .codeforiserver-1.2.0.jar to $HOME/.vscode , re-started VSC  but still getting same error.

Thank you and appreciate any help.

**Comment by basim1971** [comment]
> You can manually install the file by downloading from the [GitHub releases page](https://github.com/ThePrez/CodeForIBMiServer/releases) and creating a `$HOME/.vscode` directory and storing the file there. For instance, `$HOME/.vscode/codeforiserver-1.0.0-alpha-33.jar`)
> 
> Please note, however, that new releases of the `vscode-db2i` extension often require new versions of this server component, so you will need to redo this operation with every release

Sorry for my late reply. Thanks for your support. Can you please clarify where  i need to copy the jar file ? In the ibm i server ? In my local pc ? Can you clarify what do you mean for  "$HOME/.vscode directory "
Thanks

**Comment by worksofliam** [comment]
@basim1971 Can you ensure you're using vscode-db2i 0.4.1?

**Comment by basim1971** [comment]
@worksofliam  yes i have installe version 0.4.1

**Comment by worksofliam** [comment]
@basim1971 Was this fixed with 0.4.1?

**Comment by basim1971** [comment]
Unfortunately no

**Comment by basim1971** [comment]
@worksofliam  can you address me how install it ? Thanks

**Comment by worksofliam** [comment]
@basim1971 try upgrading to 0.5.2 and it should install this time. It will no longer ask you.
