### ISSUE TITLE
Have SQL JOB message appear only once then remember my seting

### ISSUE THREAD

**Issue by m-tyler** [codefori/vscode-db2i#120]
**Describe the enhancement**
Is it feasible to make the start up question remember what I asked it to do and not ask unless the question is not found in the settings?

I typically do not want to start the server job (so I click No), so I am okay with being asked if I attempt to do an action that requires it. 

**To Reproduce**

1. Start up product
2. Connect to IBM i extension
3. Message appears, every time.

**Screenshots**
![image](https://github.com/halcyon-tech/vscode-db2i/assets/1353665/7e81643b-1773-4085-9a26-00c9c4fe5de8)

**Environment**

 - OS: [Windows 10]
 - VS Code [1.81]
 - Extension Version [e.g. 0.4.1]

**Additional context**

**Comment by worksofliam** [comment]
Seems to me like we need a 'Never' option?

**Comment by m-tyler** [comment]
I don't know, but whenever you try an action like run an SQL statement from an .SQL or .INB document then it routes the statement through the new DB processor and ask to start the job anyway (if not started), so maybe its a no setting found message instead? 

I just see a lot more notifications and questions pop up with the last few releases, they tend to quietly go away, so maybe I am making more of it than I should. 

But if Never allowed the message to `Never` appear then I am good with that direction.

**Comment by worksofliam** [comment]
Makes sense, but for the record, you will only see that message if you try to run a statement and no job is running.

**Comment by m-tyler** [comment]
That is a direction I would prefer unless there is something that I don't realize needs the SQL JOB and wouldn't ask me to start it.

**Comment by ThePrez** [comment]
Most things in the extension use the SQL job, though, including the schema browser (and soon, the SQL editor). 

What tasks do you expect to accomplish without an SQL job?

**Comment by m-tyler** [comment]
I don't use the DB2 for i extension that much and when I do use it the extension will ask me to start a job, which is pleasant to me.  I was just wondering if the initial start up message mentioned in the OP can be set to remember my choice after the first time I select it.

**Comment by worksofliam** [comment]
There are now four options:

* Yes - just this once
* Always - always start a job up for me
* No - no, just this once
* Never - use this to never be asked on startup again
