### ISSUE TITLE
Show code and state in error log 

### ISSUE THREAD

**Issue by worksofliam** [codefori/vscode-db2i#133]

**Comment by worksofliam** [comment]
@ThePrez Any chance we can get the code and state as additional props if available back in the QueryResponse?

```
{
  "id": "query4",
  "error": "Token SASDFADSF was not valid. Valid tokens: ( CL END GET SET TAG CALL DROP FREE HOLD LOCK OPEN WITH.",
  "success": false
}
```

**Comment by ThePrez** [comment]
Sure. Add me as an assignee, please

**Comment by worksofliam** [comment]
I can see it coming back in 1.4.5 - thanks!

<img width="634" alt="image" src="https://github.com/codefori/vscode-db2i/assets/3708366/69e7a0f1-0bfd-4669-885a-77a3f1cd9267">
