### ISSUE TITLE
DB2 for i - Schema Browser - Lists for tables, indexes etc, needs a sort on name.

### ISSUE THREAD

**Issue by duieolson** [codefori/vscode-db2i#146]
Pretty straight forward actually.
When I drill down into a library in the schema browser, either into indexes, aliases, views, tables,  they all should be sorted in name order.
It doesn't look like that is happening.

![image](https://github.com/halcyon-tech/vscode-db2i/assets/124823426/e1613299-e7cc-452d-a17c-1dd8cd86c892)

**Comment by worksofliam** [comment]
They for sure are already sorted by `TABLE_NAME` ascending. 

https://github.com/halcyon-tech/vscode-db2i/blob/731d03ef384fc797f4f559f0a68b00a0950ae71d/src/database/schemas.ts#L52

**Comment by duieolson** [comment]
I am still puzzled as to how the list is retrieved and sorted.  Some of my Schema lists are sorted correctly.
I have one problem child that is all over the place(image above) that is not sorted as I would have thought it should be, or expected.  So I thought maybe it was some other file type or something...  I can't decipher it.

When I apply a filter by $ and press enter,  the result list is exactly in order and same as the sql I ran replicating your process.
![image](https://github.com/halcyon-tech/vscode-db2i/assets/124823426/11faad93-6c77-484b-83f3-ed8c220a5043)


As I look at the results of the sql used to retrieve the table list,  it is including FILE_TYPE D and S.  S being Source Files.
Not sure they should be included in a DB2 tables types of list... I mean, yeah, it's a table, but you can really do anything with it and have the Code for I on the flip side to deal with those.  Thoughts?

**Comment by worksofliam** [comment]
Fixed in #197
