### ISSUE TITLE
Shifting from a long running query --> Explain without running doesn't stop the long running query

### ISSUE THREAD

**Issue by forstie** [codefori/vscode-db2i#192]
⚠️⚠️ **How to collection debug information** ⚠️⚠️

After connecting to a system, use the 'Db2 for i Server Component' Output tab to see installation/debug information flow it. By default, it will only show installation information and errors if any. If you need to collect information for a specific job:

1. right click on any job (in the SQL Job Manager) and select the option to enabing tracing
2. recreate the issue with tracing enabled
3. right click on the same job again and get the tracing data
4. copy and paste that data into your new issue

**Describe the bug**

**To Reproduce**

**Expected behavior**

https://github.com/microsoft/vscode/issues/203855

**Screenshots**

**Environment**

 - OS: [e.g. Windows/Max]
 - Extension Version [e.g. 0.3.0]

**Additional context**

**Comment by worksofliam** [comment]
Steps to Reproduce:

ctcdb31a - db2data iasp
SELECT * FROM kraken77.ITEM_FACT order by shipmode, receiptdate; -- run and explain
SELECT * FROM kraken77.ITEM_FACT order by shipmode, receiptdate; -- Explain without running

I ran 'Run and Explain against a long running query, and then regretted the choice.
Then, I ran 'Explain without running'. ... VS makes it look like Explain without running is happening, when in fact it isn't.
You could use SQL_Cancel to whack the previous query when the user asks for sumpin different.

**Comment by worksofliam** [comment]
Will be doable with #195
