### ISSUE TITLE
Prevent output channel `IBM i` from appearing when SQL statement prefix is present

### ISSUE THREAD

**Issue by m-tyler** [codefori/vscode-db2i#200]
Prevent output channel `IBM i` from appearing when SQL statement prefix is present.

When I prefix a SQL statement that opens an editor tab the output channel is unnecessary.  I know its simple to press CTRL+J to dismiss the output channels but its tiresome when not needed. 

Thanks, Matt

**Comment by worksofliam** [comment]
@m-tyler I am not following entirely with this issue.

Any chance you can share steps to recreate?

**Comment by m-tyler** [comment]
1. write SQL statement in a tab with language type of SQL
2. prefix statement with CSV: or JSON:
3. run statement with CTRL+R

![image](https://github.com/codefori/vscode-db2i/assets/1353665/fcfe8c21-67f4-45dd-9998-c0a9245e1de5)

![image](https://github.com/codefori/vscode-db2i/assets/1353665/b63ce83c-7838-41d3-80fb-49db462ab469)

![image](https://github.com/codefori/vscode-db2i/assets/1353665/f8ceed3f-f662-480c-bafc-451f078de18b)

**Comment by worksofliam** [comment]
Got it! Yes, this might be simple enough.
