### ISSUE TITLE
Db2 for i Error

### ISSUE THREAD

**Issue by hn000246** [codefori/vscode-db2i#222]
![image](https://github.com/codefori/vscode-ibmi/assets/50391179/da6d4fbe-bd46-4499-8e8f-fbf68c680657)

Hello @worksofliam !!
I just upgrade db2 for i but i can see the Sql Job mánager anymore.
Do you know why? You can see the picture.

Best Regards,

**Comment by worksofliam** [comment]
Please share the contents of your Code for IBM i output channel after it doesn't appear.

<img width="939" alt="image" src="https://user-images.githubusercontent.com/3708366/178739532-03c8ad30-84de-4698-9904-65938f2ef651.png">

**Comment by worksofliam** [comment]
Please update to 0.10.0, which should solve your issue.

**Comment by hn000246** [comment]
Thanks @worksofliam 
Best Regards.
