### ISSUE TITLE
DB2 version 1.0.0 causes issues opening .inb documents

### ISSUE THREAD

**Issue by m-tyler** [codefori/vscode-db2i#232]
I updated to version 1.0.0, tried to open an existing (INB) notebook with only markdown text and I get the error in the image below.   If I create a new empty INB notebook, no error is presented.  I have yet to know what part of my notebook is the reason I get the error.  When I get a document that consistently reproduce the issue I will post it here for testing.  If I downgrade to 0.10.2 version I can open my notebooks. 

**Expected behavior**
Documents open without errors

**Screenshots**
Version 1.0.0
![image](https://github.com/codefori/vscode-db2i/assets/1353665/3e116443-0733-443b-a170-cbd4384fdeb0)

**Environment**

 - OS: Windows 10
 - Extension Version 1.0.0

**Comment by worksofliam** [comment]
@m-tyler can you share the Notebook? It sounds like it might have been created with the old Notebooks extension and then you tried to open it with the new one, which isn't possible since we changed the format.

**Comment by m-tyler** [comment]
File Problem.inb was created on my set up versions of DB2 for IBM i version 0.10.2.  
[problem.inb.txt](https://github.com/codefori/vscode-db2i/files/15223693/problem.inb.txt)
File Problem_2.inb was created on my set up versions of DB2 for IBM i version 1.0.0.  
[Problem_2.inb.txt](https://github.com/codefori/vscode-db2i/files/15223694/Problem_2.inb.txt)


-----
At DB2 version 0.10.2
No connection to IBM i server.
Problem.inb opens.
Problem_2.inb will not open.
-----
Once connected to a IBM i server
Problem.inb opens.
Problem_2.inb will not open.

-----
At DB2 version 1.10.0
No connection to IBM i server.
Problem.inb will not open and I receive screen shot above.
Problem_2.inb will open.

-----
Once connected to a IBM i server
Problem.inb will not open and I receive screen shot above.
Problem_2.inb will open.


I almost always create notebooks from scatch.  The one that is giving me problems and started this issue, was created last week using notebook extension version 0.0.6

|Context|Version|
|-|-|
|Code for IBM i version|2.10.1|
|Visual Studio Code version|1.88.1|
|Operating System|win32_x64|


<details>
<summary>Active extensions</summary>

```
Auto Hide (fork) (vscode-autohide-fork): 1.0.9
Calculator (calculator): 0.1.1
Code Spell Checker (code-spell-checker): 3.0.1
Code for IBM i Walkthroughs (vscode-ibmi-walkthroughs): 0.5.0
Db2 for IBM i (vscode-db2i): 1.0.0
Emmet (emmet): 1.0.0
Error Lens (errorlens): 3.17.0
Excel Viewer (gc-excelviewer): 4.2.59
Git (git): 1.0.0
Git Base (git-base): 1.0.0
GitHub (github): 0.0.1
GitHub Authentication (github-authentication): 0.0.2
Hawkeye Pathfinder (vscode-ibmi-hawkeye): 0.0.4
IBM i Debug (ibmidebug): 1.0.0
IBM i Notebooks (vscode-ibmi-notebooks): 0.0.6
JSON Language Features (json-language-features): 1.0.0
Merge Conflict (merge-conflict): 1.0.0
Node Debug Auto-attach (debug-auto-launch): 1.0.0
Overtype (overtype): 0.5.0
Partial Diff (partial-diff): 1.4.3
Rainbow CSV (rainbow-csv): 3.11.0
Rocket DevOps (rdo-vsc-ibmi): 10.3.1
TODO Highlight (vscode-todo-highlight): 1.0.5
Text Marker (Highlighter) (text-marker): 1.11.0
TypeScript and JavaScript Language Features (typescript-language-features): 1.0.0
classdiagram-ts (classdiagram-ts): 0.1.67
undefined (indent-rainbow): 8.3.1
```
</details>


<hr />


<details>
<summary>Remote system</summary>

|Setting|Value|
|-|-|
|IBM i OS|V7R5M0|
|Tech Refresh|3|
|CCSID Origin|user|
|Runtime CCSID|37|
|Default CCSID|37|
|SQL|Enabled
|Source dates|Enabled

**Comment by worksofliam** [comment]
@m-tyler if you have the old Notebooks extension, it's time to remove it. There might be some clashing.

**Comment by worksofliam** [comment]
@m-tyler remove the old extension, and Notebooks is now shipped with the database extension.

**Comment by m-tyler** [comment]
Ah, thanks.  I didn't even look at the release notes for the DB2 update.  Sorry, my mistake.  

How would I go about re-using old version notebooks with the new version code?  The issue still exists with the notebooks create using the standalone version 0.0.6.

**Comment by m-tyler** [comment]
For those that don't want to guess the patter is like the following.  I only had three "kinds" of records in my old note books.

Scan and replace
Old notebook pattern -> New notebook pattern replacement
```
"kind":1,"language":"markdown","value": ->"cell_type":"markdown","metadata":{},"source":
"kind":2,"language":"sql","value": ->"cell_type": "code","execution_count": null,"metadata": {"tags": ["sql"]},"outputs": [],"source":
"kind":2,"language":"cl","value": ->"cell_type": "code","execution_count": null,"metadata": {"tags": ["cl"]},"outputs": [],"source":
```
wrap the entire file before the outer most square brakets `[...]`  with `{"cells":[...], "metadata": { "kernelspec": { "display_name": "DB2 for IBM i", "name": "db2i" }, "language_info": { "name": "sql", "file_extension": "sql" } }, "nbformat": 4, "nbformat_minor": 0 }`
