### ISSUE TITLE
minor issue - when making CTRL+N is opened a new simple text file and not a one with a .sql extension

### ISSUE THREAD

**Issue by allthom** [codefori/vscode-db2i#236]
As said in the title, prior to latest VS Code update (I am on 1.90) when i make CTRL+N in the vscode-db2i context (v1.0.0 installed) it opened a .sql file, and it was very helpfull since i can write the statement i need and run it to see how it works, now when i make CTRL+N is opened a simple txt file and before i can run my statement i need to save it and then i can run the statement. Is there a way to have VS Code to open a .sql file?

**Comment by worksofliam** [comment]
Sadly, this is controlled by VS Code and not by the database extension.

You want this config:

<img width="750" alt="image" src="https://github.com/codefori/vscode-db2i/assets/3708366/4a829a40-d195-4894-a0ee-a6feee306d90">
