### ISSUE TITLE
Schema browser search/filter

### ISSUE THREAD

**Issue by jkdavew** [codefori/vscode-db2i#247]
Type: <b>Bug</b>

When using a schema browse/filter, the help says "show objects that start with this value" but I'm finding it's doing a "contains" search instead.

Also noticed that underscores aren't handled too well.  If I search for v_ (my goal finding views that start with that pattern), it's finding many more things (and the _ isn't factored in).  I have a feeling it could be due to the underscore in a LIKE statement.  The snippet below "may" help resolve the issue using v_ as the search example.

Presumed this is currently being done:
like '%V_%'

Adjusted:
like 'V\_%' escape '\'

Suggestion: if underscores appears in the browse/filter, prepend with a backslash.

Keep up the good work!!

Extension version: 1.0.0
VS Code version: Code 1.91.1 (f1e16e1e6214d7c44d078b1f0607b2388f29d729, 2024-07-09T22:06:49.809Z)
OS version: Windows_NT x64 10.0.22631
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|13th Gen Intel(R) Core(TM) i7-13800H (20 x 2918)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|31.59GB (11.38GB free)|
|Process Argv|--crash-reporter-id 2f019281-5e42-4fb5-8cc5-2cecaf354ddc|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
vscod805cf:30301675
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
a9j8j154:30646983
962ge761:30959799
pythongtdpath:30769146
welcomedialogc:30910334
pythonnoceb:30805159
asynctok:30898717
pythonregdiag2:30936856
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
accentitlementsc:30995553
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
chatpanelc:31048052
dsvsc021:30996838
945dj816:31013170
pythoncenvpt:31062603
a69g1124:31058053
dvdeprecation:31068756
dwnewjupyter:31046869
impr_priority:31094925
refactorc:31098050
ccplc:31098109

```

</details>

**Comment by worksofliam** [comment]
@jkdavew 

> the help says "show objects that start with this value"

Please share where this is referenced. Is in our docs or in the extension itself?

I will look into solving this for you this week.

**Comment by jkdavew** [comment]
Hi Liam,

This is referenced in the DB2 for i extension.  Clicking the "Magnifying
Glass" icon next to a schema shows the "Set filter..." prompt off to the
right.
[image: image.png]

As an example, in the prompt if you enter, "audit_" you'll find results in
the SYSTOOLS schema.  If you instead search for "a_", I'd think you'd find
nothing (since nothing starts with "a_", however results are shown.
[image: image.png]

[image: image.png]

I hope this helps to clarify.  While the "a_" search isn't a
great/practical example, it's a close representation to a search that we'd
do in our environment for "v_" denoting views by that prefix.

Thanks Liam

**Comment by worksofliam** [comment]
@jkdavew I just realized while working on a security fix I may have broken this in the next release. Here is how we're building the filter clause now:

https://github.com/codefori/vscode-db2i/pull/252/files#diff-3c7d0b76e5f5800890e460fe8b325034da2d2e64c748c47a17eff692e56374abR30

**Comment by jkdavew** [comment]
Ok, yeah I see it was a pretty significant change and that Julia is working on a fix related to it.
