### ISSUE TITLE
Cannot read properties of undefined (reading 'getFeatures') 

### ISSUE THREAD

**Issue by lgiammattei** [codefori/vscode-db2i#250]
current version 2.12.0 
after upgrading to this version when connecting to my system a sql job does not start automatically and when i go trying to browse my schema i get this error when trying to start a new sql job

**Comment by worksofliam** [comment]
The real bug is here: https://github.com/codefori/vscode-ibmi/pull/2182#pullrequestreview-2205342417

But I will make a temp fix anyway.

**Comment by lgiammattei** [comment]
thx @worksofliam

**Comment by lgiammattei** [comment]
If there is anything i can do to help let me know
