### ISSUE TITLE
Bug: Notebooks - Cannot read properties of undefined (reading 'length')

### ISSUE THREAD

**Issue by Wright4i** [codefori/vscode-db2i#261]
**Description**

![image](https://github.com/user-attachments/assets/a9d75654-b7cc-4bc1-b8bf-c8732304bc62)

**To Reproduce**

1. Create a Notebook
2. Add a `Code` block
3. Write an Insert statement
4. Execute

**Expected behavior**

```
Statement executed with no result set returned. Rows affected: 123
```

**Environment**

 - OS: Windows 11 / Mac Sonoma
 - Extension Version v1.1.4

**Comment by worksofliam** [comment]
Any statement creates this error for you I'm assuming?

@ajshedivy any chance you can take a look?

**Comment by Wright4i** [comment]
> Any statement creates this error for you I'm assuming?


Correct, all my insert statements not just those in the screenshot.

**Comment by worksofliam** [comment]
Actually I just realised this has been around for a while. We just need to handle when there are no rows back better.

Cc @ajshedivy
