### ISSUE TITLE
SQL Statment

### ISSUE THREAD

**Issue by sboisier** [codefori/vscode-db2i#282]
Hi,

Trying simple request on my IBM i System with VSCode and Code for IBM i Extension.

Table creation. This statment is working both on my iSeries Native SQL and on VSCode and even in ACS run Scripts :

CREATE TABLE QTEMP.Test (
CLE INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
Valeur CHAR(10)
);

Records insertions. This statment is working both on my iSeries Native SQL and on VSCode and even in ACS run Scripts:

INSERT INTO
QTEMP.Test (Valeur)
VALUES
('A'),
('B'),
('C'),
('D'),
('E'),
('F');

Select statment. 
This statment is working on my iSeries SQL and not on VSCode (error [SQL0104] Elément syntaxique n'est pas correct. Eléments possibles : ( + - ? : DAY INF LAG NAN RID ROW., 42601, -104) :

SELECT
CLE,
CASE
WHEN CLE = 1 THEN 'FIRST' Else VALEUR End As VALEUR
FROM
QTEMP.Test;

Maybe I'm not using the right SQL Driver in VSCode but I don't know how to check this and how to fix my problem.
Thx for helping me on this guys

**Comment by worksofliam** [comment]
I am aware of this issue but sadly I'm away from my laptop due to the impact of Helene. I will get back to this likely this weekend.

**Comment by worksofliam** [comment]
Fixed in 1.5.2 which is being released now.
