### ISSUE TITLE
Notebook (DB2 for IBM i) shows only 100 rows

### ISSUE THREAD

**Issue by zzmand** [codefori/vscode-db2i#295]
Hi, 

first of all - DB2 for IBM i / Notebook is best

only thing I'm struggling right now is 100 rows limit. When I put simple Select statement in Notebook and click on execute. Only 100 rows are displayed every time.

I'm talking about DB2 for IBM i extension. When I run same statement on IBM i Notebooks it will show all rows. 
But in this Notebook I cannot show graphs.

When I run select statement directly on  DB2 for i  I will get "Loaded 100. More available." 
Then I can us PageDown to show following rows. 
But I don't have this PageDown option in Notebook (DB2 for IBM i).

When I run same statement ( something like this - db2util "select * from admdevtod.dskgrllog" ) in terminal window under db2util all rows are displayed.

have a nice day
Dan Tomik

<hr />

⚠️ **REMOVE THIS LINE AND ANY SENSITIVE INFORMATION BELOW!** ⚠️

|Context|Version|
|-|-|
|Code for IBM i version|2.13.5|
|Visual Studio Code version|1.95.1|
|Operating System|win32_x64|

<details>
<summary>Active extensions</summary>

```
CL (vscode-clle): 1.1.7
COBOL (cobol): 24.10.26
Code for IBM i Walkthroughs (vscode-ibmi-walkthroughs): 0.5.0
Configuration Editing (configuration-editing): 1.0.0
Db2 for IBM i (vscode-db2i): 1.6.1
Emmet (emmet): 1.0.0
Error Lens (errorlens): 3.20.0
Extension Authoring (extension-editing): 1.0.0
Git (git): 1.0.0
Git Base (git-base): 1.0.0
GitHub (github): 0.0.1
IBM i Debug (ibmidebug): 2.0.1
IBM i Notebooks (vscode-ibmi-notebooks): 0.0.6
IBM i Project Explorer (vscode-ibmi-projectexplorer): 2.12.0
JSON Language Features (json-language-features): 1.0.0
JavaScript Debugger (js-debug): 1.95.1
Markdown Language Features (markdown-language-features): 1.0.0
Markdown Math (markdown-math): 1.0.0
Merge Conflict (merge-conflict): 1.0.0
Node Debug Auto-attach (debug-auto-launch): 1.0.0
Server Ready Action (debug-server-ready): 1.0.0
Source Orbit (vscode-sourceorbit): 1.0.2
TODO Highlight (vscode-todo-highlight): 1.0.5
TypeScript and JavaScript Language Features (typescript-language-features): 1.0.0
```
</details>

<hr />

<details>
<summary>Remote system</summary>

|Setting|Value|
|-|-|
|IBM i OS|V7R4M0|
|Tech Refresh|10|
|CCSID Origin|870|
|Runtime CCSID|870|
|Default CCSID|870|
|SQL|Enabled
|Source dates|Disabled

### Enabled features

|/QOpenSys/pkgs/bin|/usr/bin|/QSYS.lib/ILEDITOR.lib|/QSYS.LIB|/QIBM/ProdData/IBMiDebugService/bin|/QOpenSys/QIBM/ProdData/JavaVM/jdk80|/QOpenSys/QIBM/ProdData/JavaVM/jdk11|/QOpensys/pkgs/lib/jvm|
|-|-|-|-|-|-|-|-|
|bash|attr|GETNEWLIBL.PGM|QZDFMDB2.PGM|startDebugService.sh|64bit|64bit|openjdk-11|
|chsh|iconv|||||||
|find|setccsid|||||||
|git|tar|||||||
|grep||||||||
|ls||||||||
|md5sum||||||||
|sort||||||||
|stat||||||||
|tn5250||||||||
</details>

<details>
<summary>Shell env</summary>

```bash
BUILDLIB=ADMDEVTOD
CURLIB=ADMDEVTOD
HOME=/home/HLPATOD
HOST=IBMS3
LIBLS=QTEMP QGPL ICBSUTIL ADMLIB
LOGIN=hlpatod
LOGNAME=hlpatod
MAIL=/var/spool/mail/hlpatod
OLDPWD=/home/hlpatod
PATH=/QOpenSys/pkgs/bin:/QOpenSys/usr/bin:/usr/ccs/bin:/QOpenSys/usr/bin/X11:/usr/sbin:.:/usr/bin
PWD=/home/HLPATOD
SHELL=/QOpenSys/pkgs/bin/bash
SHLVL=1
SSH_CLIENT=10.48.206.13 29451 22
SSH_CONNECTION=10.48.206.13 29451 10.50.5.130 22
TZ=<CET>-1<CEST>,M3.5.0,M10.5.0/03:00:00
USER=hlpatod
USERNAME=HLPATOD
WORKDIR=/home/HLPATOD
_=/QOpenSys/pkgs/bin/env
```
</details>

<details>
<summary>Variants</summary>

```json
{
  "american": "#@$",
  "local": "#@$"
}
```
</details>

<details>
<summary>Errors</summary>

```json
[
  {
    "command": "/QOpenSys/usr/bin/qsh",
    "code": 1,
    "stderr": "CPF2111:  Library ILEDITOR already exists.\nCPC2206:  Ownership of object QZSHSYSTEM in QTEMP type *USRSPC changed.",
    "cwd": "/home/HLPATOD"
  },
  {
    "command": "cd '/home/hlpatod/notebook' && /QOpenSys/pkgs/bin/stat --dereference --printf=\"%A\t%h\t%U\t%G\t%s\t%Y\t%n\n\" * .*  ",
    "code": 1,
    "stderr": "/QOpenSys/pkgs/bin/stat: cannot stat '.*': No such file or directory",
    "cwd": "/home/HLPATOD"
  },
  {
    "command": "cd '/home/hlpatod/notebook/IBMS2A - notebook' && /QOpenSys/pkgs/bin/stat --dereference --printf=\"%A\t%h\t%U\t%G\t%s\t%Y\t%n\n\" * .*  ",
    "code": 1,
    "stderr": "/QOpenSys/pkgs/bin/stat: cannot stat '.*': No such file or directory",
    "cwd": "/home/HLPATOD"
  }
]
```
</details>

**Comment by worksofliam** [comment]
@zzmand I have now increased the row limit to 1000.
